shared:
  image: node:24
  steps:
    - test: echo test

jobs:
  a:
    requires: [~pr]
  b:
    requires: [ ~a ]
  c:
    requires: [~pr:foo]
  d:
    requires: [~pr:bar]
  e:
    requires: []
  f:
    requires: []
  g:
    requires: [ ~f ]
