jobs:
  main:
    requires: ~commit
    image: node:14
    steps:
      - set: |
          echo $SD_PRIVATE_PIPELINE
          echo $CONTAINER_CPU_LIMIT
  next:
    requires: main
    image: node:16
    steps:
      - echo: echo hi
