template: ibu-test/sd-ibu-pipeline-template@1.0.4
shared:
  image: node:20
jobs:
  main:
    settings:
      slack:
        channels:
          - 'slack-test1'
        statuses:
          - RUNNING
          - SUCCESS
          - FAILURE
